<?xml version="1.0" encoding="utf-8"?>
<!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by Stephen Brawner (brawner@gmail.com) 
     Commit Version: 1.6.0-4-g7f85cfe  Build Version: 1.6.7995.38578
     For more information, please see http://wiki.ros.org/sw_urdf_exporter -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">
  <xacro:include filename="robot_values.xacro"/>
  
  <link name="base_link">
  </link>

  <gazebo reference="base_link">
  </gazebo>

  <joint name="origin_joint" type="fixed">
    <parent link="base_link"/>
    <child link="origin"/>
    <origin xyz="0 0 0.35" rpy="0 0 0"/>
  </joint>
  <link
    name="origin">
    <inertial>
      <origin
        xyz="8.38288575652309E-07 0.131802961451061 0.119457737645149"
        rpy="0 0 0" />
      <mass
        value="6.31210414331163" />
      <inertia
        ixx="0.109718503078251"
        ixy="-3.107004482999E-07"
        ixz="1.27742625490502E-09"
        iyy="0.0504994066686463"
        iyz="1.92825387800283E-10"
        izz="0.157184029088834" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/origin.STL"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 ${(chassis_y / 2) - 0.08} ${chassis_z / 2}"
        rpy="0 0 ${pi / 2}" />
      <geometry>
        <box size="${chassis_x} ${chassis_y} ${chassis_z}"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="origin">
  </gazebo>

  <link
    name="differential_link">
    <inertial>
      <origin
        xyz="2.48368055802417E-08 -3.14429672888805E-08 0.0199042487071119"
        rpy="0 0 0" />
      <mass
        value="0.663253070147783" />
      <inertia
        ixx="0.000176065807329218"
        ixy="-1.74124228174769E-12"
        ixz="-2.64568230296014E-10"
        iyy="0.00533562068145632"
        iyz="-1.07943588779656E-10"
        izz="0.00530780669766808" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/differential.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/differential.STL" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="differential_link">
  </gazebo>

  <joint
    name="differential_joint" type="revolute">
    <origin
      xyz="0 0.0132475000000002 0.193421177067123"
      rpy="0 0 0" />
    <parent
      link="origin" />
    <child
      link="differential_link" />
    <axis
      xyz="0 0 1" />
    <limit effort="100" lower="-${pi / 4}" upper="${pi / 4}" velocity="0"/>
  </joint>

  <link
    name="xz_left">
    <inertial>
      <origin
        xyz="-4.64889271523106E-09 0.0353830314295401 0.0108129499116387"
        rpy="0 0 0" />
      <mass
        value="0.0155401592452895" />
      <inertia
        ixx="4.23350176895727E-06"
        ixy="3.64217998809471E-14"
        ixz="-3.64374435199193E-13"
        iyy="5.22956405101389E-07"
        iyz="1.47618341469402E-15"
        izz="4.40773318106849E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/xz_left.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/xz_left.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="link3_left"
    type="continuous">
    <origin
      xyz="-0.248132600000003 0 0.00886587323959548"
      rpy="0 0 0" />
    <parent
      link="differential_link" />
    <child
      link="xz_left" />
    <axis
      xyz="0 0 -1" />
  </joint>
  <gazebo reference="xz_left">
  </gazebo>
  <link
    name="xy_left">
    <inertial>
      <origin
        xyz="4.88970574419323E-05 0.0478926853579212 -1.29911378876635E-09"
        rpy="0 0 0" />
      <mass
        value="0.0251600949304728" />
      <inertia
        ixx="1.39101472176527E-05"
        ixy="-9.21531915994836E-11"
        ixz="7.27350532600888E-12"
        iyy="3.13190614602218E-06"
        iyz="-7.09291132933723E-13"
        izz="1.5415172628415E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/xy_left.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/xy_left.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="link4_left"
    type="continuous">
    <origin
      xyz="0 0.057190625 0.0108129496932786"
      rpy="0 0 0" />
    <parent
      link="xz_left" />
    <child
      link="xy_left" />
    <axis
      xyz="0 1 0" />
  </joint>
  <link
    name="moment_left">
    <inertial>
      <origin
        xyz="-0.0931762739376563 -0.123516160160037 -0.29938621188847"
        rpy="0 0 0" />
      <mass
        value="2.01112856146357" />
      <inertia
        ixx="0.00516957821369544"
        ixy="-0.000177768861031969"
        ixz="-0.00023860509115917"
        iyy="0.00729857222045286"
        iyz="-0.00092981195043092"
        izz="0.00746428128106379" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/moment_left.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/moment_left.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="link5_left"
    type="fixed">
    <origin
      xyz="0 0.05 0"
      rpy="0.1 0 0" />
    <parent
      link="xy_left" />
    <child
      link="moment_left" />
    <axis
      xyz="1 0 0" />
  </joint>
  <link
    name="v_sus_left">
    <inertial>
      <origin
        xyz="-0.07438360811719 -3.05545318490807E-08 -0.132224992858002"
        rpy="0 0 0" />
      <mass
        value="2.82440298792168" />
      <inertia
        ixx="0.00465480896029421"
        ixy="3.74450543361103E-09"
        ixz="-0.00035547177476203"
        iyy="0.0114377704380639"
        iyz="-0.000197779148914569"
        izz="0.011437765959161" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/v_sus_left.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/v_sus_left.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="link6_left"
    type="continuous">
    <origin
      xyz="-0.0898452499999906 0.210138998231297 -0.289141657509324"
      rpy="0 0 0" />
    <parent
      link="moment_left" />
    <child
      link="v_sus_left" />
    <axis
      xyz="1 0 0" />
  </joint>
  <link
    name="back_wheel_left">
    <inertial>
      <origin
        xyz="-0.0606509662118138 -1.56979517218492E-06 -3.03360577857958E-06"
        rpy="0 0 0" />
      <mass
        value="0.872355305254737" />
      <inertia
        ixx="0.00417315628555038"
        ixy="6.73577382185176E-12"
        ixz="-4.06571320196708E-12"
        iyy="0.00262052621586287"
        iyz="-3.07584023707993E-08"
        izz="0.00262053974408054" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/back_wheel_left.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="-${wheel_length / 2} 0 0"
        rpy="0 -${pi / 2} 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="wbl"
    type="continuous">
    <origin
      xyz="-0.138440000000004 0.186959032945723 -0.186959032945724"
      rpy="0 0 0" />
    <parent
      link="v_sus_left" />
    <child
      link="back_wheel_left" />
    <axis
      xyz="-1 0 0" />
    <limit
      lower="3000"
      upper="10000"
      effort="0"
      velocity="0" />
    <dynamics damping="0.4"/>
  </joint>

  <link
    name="mid_wheel_left">
    <inertial>
      <origin
        xyz="-0.0606509646736957 -3.39118563014162E-06 -4.10304526021754E-07"
        rpy="0 0 0" />
      <mass
        value="0.872355274582066" />
      <inertia
        ixx="0.00417315625365433"
        ixy="9.345385978402E-13"
        ixz="-8.97226752263588E-12"
        iyy="0.00262050679468228"
        iyz="1.75312063319718E-08"
        izz="0.00262055913309501" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/mid_wheel_left.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="-${wheel_length / 2} 0 0"
        rpy="0 -${pi / 2} 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="wml"
    type="continuous">
    <origin
      xyz="-0.138440000000003 -0.186959032945725 -0.186959032945722"
      rpy="0 0 0" />
    <parent
      link="v_sus_left" />
    <child
      link="mid_wheel_left" />
    <axis
      xyz="-1 0 0" />
    <limit
      lower="3000"
      upper="10000"
      effort="0"
      velocity="0" />
    <dynamics damping="0.4"/>
  </joint>

  <link
    name="front_wheel_left">
    <inertial>
      <origin
        xyz="-0.0606509662118164 4.48833228916534E-07 -3.38608464470203E-06"
        rpy="0 0 0" />
      <mass
        value="0.872355305254721" />
      <inertia
        ixx="0.00417315628555027"
        ixy="7.85044381615288E-12"
        ixz="5.2081601804733E-13"
        iyy="0.00262055951728101"
        iyz="-1.69588825066961E-08"
        izz="0.00262050644266229" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/front_wheel_left.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="-${wheel_length / 2} 0 0"
        rpy="0 -${pi / 2} 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="wfl"
    type="continuous">
    <origin
      xyz="-0.171135249999997 -0.301408815255102 -0.432914143794077"
      rpy="0 0 0" />
    <parent
      link="moment_left" />
    <child
      link="front_wheel_left" />
    <axis
      xyz="-1 0 0" />
    <limit
      lower="3000"
      upper="10000"
      effort="0"
      velocity="0" />
    <dynamics damping="0.4"/>
  </joint>

  <link
    name="xz_right">
    <inertial>
      <origin
        xyz="-4.64889279849778E-09 0.0353830314295419 0.0108129499116388"
        rpy="0 0 0" />
      <mass
        value="0.0155401592452895" />
      <inertia
        ixx="4.23350176895728E-06"
        ixy="3.64218004552526E-14"
        ixz="-3.64374435459882E-13"
        iyy="5.2295640510139E-07"
        iyz="1.47618383529035E-15"
        izz="4.4077331810685E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/xz_right.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/xz_right.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="link3_right"
    type="continuous">
    <origin
      xyz="0.248132599999997 0 0.00707993573959712"
      rpy="0 0 0" />
    <parent
      link="differential_link" />
    <child
      link="xz_right" />
    <axis
      xyz="0 0 -1" />
  </joint>
  <link
    name="xy_right">
    <inertial>
      <origin
        xyz="-4.88970574422376E-05 0.0478926853579229 1.2991137332552E-09"
        rpy="0 0 0" />
      <mass
        value="0.0251600949304728" />
      <inertia
        ixx="1.39101472176527E-05"
        ixy="9.21531915995532E-11"
        ixz="7.27350532727311E-12"
        iyy="3.13190614602218E-06"
        iyz="7.09291133019552E-13"
        izz="1.5415172628415E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/xy_right.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/xy_right.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="link4_right"
    type="continuous">
    <origin
      xyz="0 0.057190625 0.0108129496932787"
      rpy="0 0 0" />
    <parent
      link="xz_right" />
    <child
      link="xy_right" />
    <axis
      xyz="0 1 0" />
  </joint>
  <link
    name="moment_right">
    <inertial>
      <origin
        xyz="0.0922237739376568 -0.123614286522059 -0.299386222826408"
        rpy="0 0 0" />
      <mass
        value="2.01112856146357" />
      <inertia
        ixx="0.00516957821369544"
        ixy="0.000177705226681604"
        ixz="0.000238601639100839"
        iyy="0.00729857437451202"
        iyz="-0.000928333468535199"
        izz="0.00746427912700465" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/moment_right.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/moment_right.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="link5_right"
    type="fixed">
    <origin
      xyz="0 0.05 0"
      rpy="0 0 0" />
    <parent
      link="xy_right" />
    <child
      link="moment_right" />
    <axis
      xyz="-1 0 0" />
  </joint>
  <link
    name="v_sus_right">
    <inertial>
      <origin
        xyz="0.0743836081171779 3.05545835854737E-08 -0.132224992858358"
        rpy="0 0 0" />
      <mass
        value="2.82440298792168" />
      <inertia
        ixx="0.00465480896029421"
        ixy="3.74450541644225E-09"
        ixz="0.000355471774762031"
        iyy="0.0114377704380639"
        iyz="0.000197779148914571"
        izz="0.011437765959161" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/v_sus_right.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/v_sus_right.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="link6_right"
    type="continuous">
    <origin
      xyz="0.0888927500000046 0.210036328970344 -0.289141657509324"
      rpy="0 0 0" />
    <parent
      link="moment_right" />
    <child
      link="v_sus_right" />
    <axis
      xyz="-1 0 0" />
  </joint>
  <link
    name="mid_wheel_right">
    <inertial>
      <origin
        xyz="0.0606509646736914 -3.39420691142234E-06 3.84512094109279E-07"
        rpy="0 0 0" />
      <mass
        value="0.872355274582068" />
      <inertia
        ixx="0.00417315625365434"
        ixy="-8.663027333556E-13"
        ixz="-8.97911125295135E-12"
        iyy="0.00262050706425384"
        iyz="-1.79270598498908E-08"
        izz="0.00262055886352346" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/mid_wheel_right.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="${wheel_length / 2} 0 0"
        rpy="0 -${pi / 2} 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="wmr"
    type="continuous">
    <origin
      xyz="0.13844 -0.186959032945726 -0.186959032945724"
      rpy="0 0 0" />
    <parent
      link="v_sus_right" />
    <child
      link="mid_wheel_right" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="3000"
      upper="10000"
      effort="0"
      velocity="0" />
    <dynamics damping="0.4"/>
  </joint>

  <link
    name="back_wheel_right">
    <inertial>
      <origin
        xyz="0.0606509646736954 -2.99058663155716E-06 -1.64857812440244E-06"
        rpy="0 0 0" />
      <mass
        value="0.872355274582065" />
      <inertia
        ixx="0.0041731562536543"
        ixy="4.74732649588982E-12"
        ixz="-5.51090060940716E-12"
        iyy="0.00262054133497807"
        iyz="-3.03464061491934E-08"
        izz="0.00262052459279919" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/back_wheel_right.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="${wheel_length / 2} 0 0"
        rpy="0 -${pi / 2} 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="wbr"
    type="continuous">
    <origin
      xyz="0.138439999999995 0.186959032945722 -0.186959032945724"
      rpy="0 0 0" />
    <parent
      link="v_sus_right" />
    <child
      link="back_wheel_right" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="3000"
      upper="10000"
      effort="0"
      velocity="0" />
    <dynamics damping="0.4"/>
  </joint>

  <link
    name="front_wheel_right">
    <inertial>
      <origin
        xyz="0.0606509646736964 6.94867942352406E-08 -3.41521010865931E-06"
        rpy="0 0 0" />
      <mass
        value="0.87235527458206" />
      <inertia
        ixx="0.00417315625365428"
        ixy="9.01464098758403E-12"
        ixz="3.3338362944799E-13"
        iyy="0.00262055323296604"
        iyz="2.41108908632861E-08"
        izz="0.00262051269481119" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find billee_bot)/meshes/front_wheel_right.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="${wheel_length / 2} 0 0"
        rpy="0 -${pi / 2} 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="wfr"
    type="continuous">
    <origin
      xyz="0.170182749999999 -0.301511484516051 -0.432914143794079"
      rpy="0 0 0" />
    <parent
      link="moment_right" />
    <child
      link="front_wheel_right" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="3000"
      upper="10000"
      effort="0"
      velocity="0" />
    <dynamics damping="0.4"/>
  </joint>
</robot>